apiVersion: v1
kind: Secret
metadata:
  name: daln-backend-secret
type: Opaque
stringData:
  USER_DATABASE_URL: mongodb+srv://nguyen1976:nguyen1976@cluster0.zhqfsbn.mongodb.net/user-service?retryWrites=true&w=majority&appName=Cluster0
  CHAT_DATABASE_URL: mongodb+srv://nguyen1976:nguyen1976@cluster0.zhqfsbn.mongodb.net/chat-service?retryWrites=true&w=majority&appName=Cluster0
  NOTIFICATION_DATABASE_URL: mongodb+srv://nguyen1976:nguyen1976@cluster0.zhqfsbn.mongodb.net/notification-service?retryWrites=true&w=majority&appName=Cluster0
  RABBITMQ_URL: amqps://qsymcksd:kbu3rKG3GWGG2plExuUJCBf8YmGIcYn8@kingfisher.lmq.cloudamqp.com/qsymcksd
  REDIS_USERNAME: default
  REDIS_PASSWORD: ''
  R2_ACCESS_KEY: 8b9b59ce9fadedd8548dc2e50c130b93
  R2_SECRET_KEY: 4cf235b1ff3c0363281d06662791bc87ef1993e52a5979075af5165f838bfafe
  R2_ENDPOINT: https://16f3ac771d7586138a66292f472ad828.r2.cloudflarestorage.com
  R2_BUCKET: chat-real-time
  R2_PUBLIC_URL: https://pub-67972bb2abe744789d51c86dc986ec38.r2.dev
  SMTP_USER: nguyen2202794@gmail.com
  SMTP_PASS: rsvf vsyl hesq umny
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: '587'
