version: 0.2

phases: 
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com
  build:
    commands:
      - docker build --platform=linux/amd64 -t user -f backend/apps/user/Dockerfile backend
      - docker tag user:latest 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com/user:latest

      - docker build --platform=linux/amd64 -t realtime-gateway -f backend/apps/realtime-gateway/Dockerfile backend
      - docker tag realtime-gateway:latest 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com/realtime-gateway:latest

      - docker build --platform=linux/amd64 -t notification -f backend/apps/notification/Dockerfile backend
      - docker tag notification:latest 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com/notification:latest

      - docker build --platform=linux/amd64 -t chat -f backend/apps/chat/Dockerfile backend
      - docker tag chat:latest 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com/chat:latest
  post_build:
    commands:
      - docker push 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com/user:latest
      - docker push 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com/realtime-gateway:latest
      - docker push 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com/notification:latest
      - docker push 435788423238.dkr.ecr.ap-southeast-2.amazonaws.com/chat:latest