export const ROUTING_RMQ = {
  USER_CREATED: 'user.created',
  USER_REGISTER_OTP: 'user.registerOtp',
  USER_MAKE_FRIEND: 'user.makeFriend',
  USER_UPDATE_STATUS_MAKE_FRIEND: 'user.updateStatusMakeFriend',
  MESSAGE_SEND: 'message.send',
  USER_UPDATED: 'user.updated',
  EMIT_REALTIME_EVENT: 'realtime.emitEvent',
  SEND_MESSAGE: 'realtime.sendMessage',
  USER_OFFLINE: 'user.offline',
  USER_ONLINE: 'user.online',
  USER_TYPING: 'user.typing',
  MESSAGE_READ: 'message.read',
  UPDATE_MESSAGE_READ: 'message.updateRead',
}
